-- CreateEnum
CREATE TYPE "PositionTitle" AS ENUM ('CHAIRMAN', 'VICE_CHAIRMAN', 'CEO', 'PRESIDENT', 'VICE_PRESIDENT', 'SENIOR_ADVISOR_VP', 'PARTNER', 'EXECUTIVE_DIRECTOR', 'EXECUTIVE_OFFICER', 'MANAGING_DIRECTOR', 'MANAGING_OFFICER', 'STANDING_ADVISOR', 'NON_STANDING_ADVISOR', 'DIRECTOR', 'MANAGER', 'SENIOR', 'ASSOCIATE', 'CHIEF_STAFF', 'SENIOR_STAFF', 'STAFF', 'INTERN', 'PENDING');

-- CreateEnum
CREATE TYPE "JobGrade" AS ENUM ('PARTNER_KICPA_STAFF_DIRECTOR_REGISTERED', 'PARTNER_KICPA_STAFF_REGISTERED', 'PARTNER_AICPA_STAFF', 'PARTNER_TAX_ACCOUNTANT', 'KICPA_REGISTERED');

-- AlterTable
ALTER TABLE "employees" DROP COLUMN "position",
ADD COLUMN     "jobGrade" "JobGrade",
ADD COLUMN     "positionTitle" "PositionTitle";

